#!{{ pkgPathFor "core/bash" }}/bin/bash

set -e
exec 2>&1

echo "Executing reticulum run hook"

export LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export MIX_ENV=prod
export PORT={{cfg.phx.port}}

# Needed because calling fix_interpreter corrupts escript files
[[ ! -f /usr/bin/env ]] && ln -s "$(pkg_path_for coreutils)/bin/env" /usr/bin/env

exec {{ pkg.path }}/bin/conform --conf {{ pkg.svc_config_path }}/ret.prod.conf --schema {{ pkg.svc_config_path }}/ret.schema.exs --config var/sys.config --output-dir var
exec {{ pkg.path }}/bin/ret foreground
